/**
 * Auth Constants
 */

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

export const USER_LOADING_REQUEST = "USER_LOADING_REQUEST";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";
export const USER_LOADING_FAIL = "USER_LOADING_FAIL";

/**
 * Supplier Constants
 */

export const SUPPLIER_GET_ALL_LIST_REQUEST = "SUPPLIER_GET_ALL_LIST_REQUEST";
export const SUPPLIER_GET_ALL_LIST_SUCCESS = "SUPPLIER_GET_ALL_LIST_SUCCESS";
export const SUPPLIER_GET_ALL_LIST_FAIL = "SUPPLIER_GET_ALL_LIST_FAIL";

export const SUPPLIER_SET_ID = "SUPPLIER_SET_ID";
export const SUPPLIER_REMOVE_ID = "SUPPLIER_REMOVE_ID";

export const SUPPLIER_DEL_REQUEST = "SUPPLIER_DEL_REQUEST";
export const SUPPLIER_DEL_SCCCESS = "SUPPLIER_DEL_SCCCESS";
export const SUPPLIER_DEL_FAIL = "SUPPLIER_DEL_FAIL";

export const SUPPLIER_CLEAR_MESSAGES = "SUPPLIER_CLEAR_MESSAGES";
/*
 *Add Supplier Constants
 */

export const SUPPLIER_ADD_REQUEST = "SUPPLIER_ADD_REQUEST";
export const SUPPLIER_ADD_SUCCESS = "SUPPLIER_ADD_SUCCESS";
export const SUPPLIER_ADD_FAIL = "SUPPLIER_ADD_FAIL";

/*
Supplier Product 
*/

export const SUPPLIER_PRODUCT_ADD_REQUEST = "SUPPLIER_PRODUCT_ADD_REQUEST";
export const SUPPLIER_PRODUCT_ADD_SUCCESS = "SUPPLIER_PRODUCT_ADD_SUCCESS";
export const SUPPLIER_PRODUCT_ADD_FAIL = "SUPPLIER_PRODUCT_ADD_FAIL";

export const SUPPLIER_PRODUCT_LIST_REQUEST = "SUPPLIER_PRODUCT_LIST_REQUEST";
export const SUPPLIER_PRODUCT_LIST_SUCCESS = "SUPPLIER_PRODUCT_LIST_SUCCESS";
export const SUPPLIER_PRODUCT_LIST_FAIL = "SUPPLIER_PRODUCT_LIST_FAIL";

export const SUPPLIER_PRODUCT_DEL_REQUEST = "SUPPLIER_PRODUCT_DEL_REQUEST";
export const SUPPLIER_PRODUCT_DEL_SCCCESS = "SUPPLIER_PRODUCT_DEL_SCCCESS";
export const SUPPLIER_PRODUCT_DEL_FAIL = "SUPPLIER_PRODUCT_DEL_FAIL";

export const SUPPLIER_PRODUCT_CLEAR_MESSAGES =
  "SUPPLIER_PRODUCT_CLEAR_MESSAGES";

/*
Orders 
*/

export const ORDER_SUPPLIER_GET_REQUEST = "ORDER_SUPPLIER_GET_REQUEST";
export const ORDER_SUPPLIER_GET_SCCUESS = "ORDER_SUPPLIER_GET_SCCUESS";
export const ORDER_SUPPLIER_GET_FAIL = "ORDER_SUPPLIER_GET_FAIL";

export const ORDER_CLEAR_MESSAGES = "ORDER_CLEAR_MESSAGES";


/*
Supplier Loader
*/
export const SUPPLIER_LOADER_ADD_REQUEST = 'SUPPLIER_LOADER_ADD_REQUEST'
export const SUPPLIER_LOADER_ADD_SCCUESS = 'SUPPLIER_LOADER_ADD_SCCUESS'
export const SUPPLIER_LOADER_ADD_FAIL = 'SUPPLIER_LOADER_ADD_FAIL'